TASK_MAPPING = {
    "1-1.ADE-ADE identification": "ADE-Identification",
    "1-2.ADE-ADE relation": "ADE-Extraction",
    "1-3.ADE-Drug dosage": "ADE-Drug dosage",
    "3-2.BARR2-resolution": "BARR2",
    "5.BrainMRI-AIS": "BrainMRI-AIS",
    "6.Brateca.hospitalization": "Brateca-Hospitalization",
    "6.Brateca.mortality": "Brateca-Mortality",
    "7.Cantemist.CODING": "Cantemist-Coding",
    "7.Cantemist.NER": "Cantemis-NER",
    "7.Cantemist.Norm": "Cantemis-Norm",
    "8.CARES.area": "CARES-Area",
    "8.CARES.icd10_block": "CARES ICD10 Block",
    "8.CARES.icd10_chapter": "CARES-ICD10 Chapter",
    "8.CARES.icd10_sub_block": "CARES-ICD10 Subblock",
    "9.CHIP-CDEE": "CHIP-CDEE",
    "12.C-EMRS": "C-EMRS",
    "17-1.CLEF_eHealth_2020_CodiEsp_corpus-ICD-10-CM": "CodiEsp-ICD-10-CM",
    "17-2.CLEF_eHealth_2020_CodiEsp_corpus-ICD-10-PCS": "CodiEsp-ICD-10-PCS",
    "19.ClinicalNotes-UPMC": "ClinicalNotes-UPMC",
    "20.clinical records from the Mexican Social Security Institute": "PPTS",
    "21.CLINpt": "CLINpt-NER",
    "22.CLIP": "CLIP",
    "23.cMedQA": "cMedQA",
    "26.DialMed": "DialMed",
    "27.DiSMed": "DiSMed-NER",
    "28.MIE": "MIE",
    "29.EHRQA.primary_department": "EHRQA-Primary department",
    "29.EHRQA.qa": "EHRQA-QA",
    "29.EHRQA.sub_department": "EHRQA-Sub department",
    "31.Ex4CDS": "Ex4CDS",
    "33.GOUT-CC.consensus": "GOUT-CC-Consensus",
    "35.n2c2 2006 - De-identification": "n2c2 2006-De-identification",
    "37.i2b2-2009-Medication-Extraction-Challenge": "Medication extraction",
    "38-1.i2b2-2010-Relations-Challenge-concept": "n2c2 2010-Concept",
    "38-2.i2b2-2010-Relations-Challenge-assertion": "n2c2 2010-Assertion",
    "38-3.i2b2-2010-Relations-Challenge-relation": "n2c2 2010-Relation",
    "41.n2c2 2014 - De-identification": "n2c2 2014-De-identification",
    "43.IMCS-V2-NER": "IMCS-V2-NER",
    "46.Japanese Case Reports": "JP-STS",
    "48.meddocan": "meddocan",
    "51.MEDIQA_2019_Task2_RQE": "MEDIQA 2019-RQE",
    "55.MedNLI": "MedNLI",
    "57.MedSTS": "MedSTS",
    "62.mtsamples": "MTS",
    "63.MTSamples-temporal annotation": "MTS-Temporal",
    "65.n2c2-2018-Track2-Adverse-Drug-Events-and-Medication-Extraction": "n2c2 2018-ADE&medication",
    "66-1.NorSynthClinical-entity": "NorSynthClinical-NER",
    "66-2.NorSynthClinical-relation": "NorSynthClinical-RE",
    "68.NUBES": "NUBES",
    "76-1.MTS-Dialog-MEDIQA-2023-chat-task-A": "MEDIQA 2023-chat-A",
    "76-2.MTS-Dialog-MEDIQA-2023-sum-task-A": "MEDIQA 2023-sum-A",
    "76-3.MTS-Dialog-MEDIQA-2023-sum-task-B": "MEDIQA 2023-sum-B",
    "80.RuMedDaNet": "RuMedDaNet",
    "81.CHIP-CDN": "CBLUE-CDN",
    "82.CHIP-CTC": "CHIP-CTC",
    "83.CHIP-MDCFNPC": "CHIP-MDCFNPC",
    "84.MedDG": "MedDG",
    "85.IMCS-V2-SR": "IMCS-V2-SR",
    "86.IMCS-V2-MRG": "IMCS-V2-MRG",
    "87.IMCS-V2-DAC": "IMCS-V2-DAC",
    "90-1.n2c2 2014 - Heart Disease Challenge - Diabete": "n2c2 2014-Diabetes",
    "90-2.n2c2 2014 - Heart Disease Challenge - CAD": "n2c2 2014-CAD",
    "90-3.n2c2 2014 - Heart Disease Challenge - Hyperlipidemia": "n2c2 2014-Hyperlipidemia",
    "90-4.n2c2 2014 - Heart Disease Challenge - Hypertension": "n2c2 2014-Hypertension",
    "90-8.n2c2 2014 - Heart Disease Challenge - Medication": "n2c2 2014-Medication",
    "91-1.CAS.label": "CAS-label",
    "91-2.CAS.evidence": "CAS-evidence",
    "93.RuMedNLI": "RuMedNLI",
    "94.RuDReC": "RuDReC-NER",
    "95.NorSynthClinical-PHI": "NorSynthClinical-PHI",
    "96.RuCCoN.NER": "RuCCoN",
    "97.CLISTER": "CLISTER",
    "98.BRONCO150.NER_status": "BRONCO150-NER&Status",
    "99.CARDIO:DE": "CARDIO-DE",
    "100.GraSSCo_PHI": "GraSSCo PHI",
    "101.IFMIR.IncidentType": "IFMIR-Incident type",
    "101.IFMIR.NER": "IFMIR-NER",
    "101.IFMIR.NER_factuality": "IFMIR - NER&factuality",
    "102.iCorpus": "iCorpus",
    "103.icliniq-10k": "icliniq-10k",
    "104.HealthCareMagic-100k": "HealthCareMagic-100k",
    "105.MIMIC-IV CDM": "MIMIC-IV CDM",
    "106.MIMIC-III Outcome.LoS": "MIMIC-III Outcome.LoS",
    "106.MIMIC-III Outcome.Mortality": "MIMIC-III Outcome.Mortality",
    "107.MIMIC-IV BHC": "MIMIC-IV BHC",
    "108.MIMIC-IV DiReCT.Dis": "MIMIC-IV DiReCT.Dis",
    "108.MIMIC-IV DiReCT.PDD": "MIMIC-IV DiReCT.PDD"
}


DATA_ACCESS_MAP = {
    "OA": "Open Access",
    "R": "Regulated",
    "P": "Regulated",
    "N": "Regulated"
}

# Mappings
DOMAIN_MAPPING = {
    "General": "General",
    "Medical": "Medical"
}

# In the filter, there should only be two categories (Open, Private)
# In the table itself, there should be more categories
LICENSE_MAPPING = {
    "Baichuan-M1-14B": "Open Source",
    "MIT": "Open Source",
    "Gemma": "Open Source",
    "Llama-3.1": "Open Source",
    "Llama-3.3": "Open Source",
    "Apache 2.0": "Open Source",
    "PhysioNet Credentialed Health Data License 1.5.0": "Open Source",
    "Llama-3": "Open Source",
    "MRL": "Open Source",
    "Qwen": "Open Source",
    "Nexusflow Research License": "Open Source",
    "Proprietary": "Proprietary",
    "Llama-4": "Open Source",
    "Health AI Developer Foundations terms of use": "Open Source",
    "llama2": "Open Source"
}
    